2020-10-06 19:33:06,661 ERROR: Exception on /index [GET] [in c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Joseph Staresinovic\website\app\routes.py", line 37, in index
    return render_template('index.html', title='Home', form=form,
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\jinja2\loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Joseph Staresinovic\website\templates\index.html", line 24, in template
    {% endfor %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endfor'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2020-10-06 19:33:24,007 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:45]
2020-10-06 19:33:31,799 ERROR: Exception on /index [GET] [in c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Joseph Staresinovic\website\app\routes.py", line 37, in index
    return render_template('index.html', title='Home', form=form,
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\jinja2\loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\joseph staresinovic\appdata\local\programs\python\python38\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Joseph Staresinovic\website\templates\index.html", line 24, in template
    {% endfor %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endfor'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2020-10-06 19:34:05,924 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:45]
2020-10-06 19:37:42,285 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:45]
2020-10-06 19:38:51,361 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:45]
2020-10-06 19:42:45,160 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:45]
2020-10-06 19:59:13,571 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:47]
2020-10-06 20:16:49,815 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:47]
2020-10-06 20:35:40,249 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:47]
2020-10-06 20:39:38,417 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:47]
2020-10-08 00:25:03,398 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:50]
2020-10-09 19:16:07,747 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-09 19:16:39,028 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-09 19:16:47,598 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-09 19:20:45,427 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-09 23:54:34,259 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-09 23:55:08,330 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-10 00:25:14,601 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-10 01:00:05,500 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-10 13:28:04,568 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-10 13:31:13,157 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-10 13:31:23,127 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-10 13:37:36,745 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-10 13:37:44,226 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
2020-10-10 16:16:19,793 INFO: Serial Agony startup [in C:\Users\Joseph Staresinovic\website\app\__init__.py:55]
